package com.sqli.rh_manager.entities;
// Generated Dec 19, 2013 6:37:54 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bu generated by hbm2java
 */
@Entity
@Table(name="bu"
    ,catalog="rh_manager"
)
public class Bu  implements java.io.Serializable {


     private int id;
     private String bu;
     private Set<Collaborateur> collaborateurs = new HashSet<Collaborateur>(0);

    public Bu() {
    }

	
    public Bu(int id) {
        this.id = id;
    }
    public Bu(int id, String bu, Set<Collaborateur> collaborateurs) {
       this.id = id;
       this.bu = bu;
       this.collaborateurs = collaborateurs;
    }
   
     @Id 
    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="BU", length=254)
    public String getBu() {
        return this.bu;
    }
    
    public void setBu(String bu) {
        this.bu = bu;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="bu")
    public Set<Collaborateur> getCollaborateurs() {
        return this.collaborateurs;
    }
    
    public void setCollaborateurs(Set<Collaborateur> collaborateurs) {
        this.collaborateurs = collaborateurs;
    }




}


