package com.sqli.rh_manager.entities;
// Generated Dec 19, 2013 6:37:54 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Compte generated by hbm2java
 */
@Entity
@Table(name="compte"
    ,catalog="rh_manager"
)
public class Compte  implements java.io.Serializable {


     private int id;
     private Profile profile;
     private String login;
     private String password;
     private String email;
     private Boolean activation;
     private Set<ManagerRhStatus> managerRhStatuses = new HashSet<ManagerRhStatus>(0);

    public Compte() {
    }

	
    public Compte(int id, Profile profile) {
        this.id = id;
        this.profile = profile;
    }
    public Compte(int id, Profile profile, String login, String password, String email, Boolean activation, Set<ManagerRhStatus> managerRhStatuses) {
       this.id = id;
       this.profile = profile;
       this.login = login;
       this.password = password;
       this.email = email;
       this.activation = activation;
       this.managerRhStatuses = managerRhStatuses;
    }
   
     @Id 
    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Profile", nullable=false)
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }
    
    @Column(name="Login", length=254)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    
    @Column(name="Password", length=254)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="Email", length=254)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="Activation")
    public Boolean getActivation() {
        return this.activation;
    }
    
    public void setActivation(Boolean activation) {
        this.activation = activation;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="compte")
    public Set<ManagerRhStatus> getManagerRhStatuses() {
        return this.managerRhStatuses;
    }
    
    public void setManagerRhStatuses(Set<ManagerRhStatus> managerRhStatuses) {
        this.managerRhStatuses = managerRhStatuses;
    }




}


