package com.sqli.rh_manager.entities;
// Generated Dec 19, 2013 6:37:54 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Droit generated by hbm2java
 */
@Entity
@Table(name="droit"
    ,catalog="rh_manager"
)
public class Droit  implements java.io.Serializable {


     private int id;
     private String droit;
     private Set<Profile> profiles = new HashSet<Profile>(0);

    public Droit() {
    }

	
    public Droit(int id) {
        this.id = id;
    }
    public Droit(int id, String droit, Set<Profile> profiles) {
       this.id = id;
       this.droit = droit;
       this.profiles = profiles;
    }
   
     @Id 
    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="Droit", length=254)
    public String getDroit() {
        return this.droit;
    }
    
    public void setDroit(String droit) {
        this.droit = droit;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="profile_droit", catalog="rh_manager", joinColumns = { 
        @JoinColumn(name="Droit", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Profile", nullable=false, updatable=false) })
    public Set<Profile> getProfiles() {
        return this.profiles;
    }
    
    public void setProfiles(Set<Profile> profiles) {
        this.profiles = profiles;
    }




}


