package com.sqli.rh_manager.entities;
// Generated Dec 19, 2013 6:37:54 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ecole generated by hbm2java
 */
@Entity
@Table(name="ecole"
    ,catalog="rh_manager"
)
public class Ecole  implements java.io.Serializable {


     private int id;
     private String nom;
     private Character type;
     private Set<Diplome> diplomes = new HashSet<Diplome>(0);

    public Ecole() {
    }

	
    public Ecole(int id) {
        this.id = id;
    }
    public Ecole(int id, String nom, Character type, Set<Diplome> diplomes) {
       this.id = id;
       this.nom = nom;
       this.type = type;
       this.diplomes = diplomes;
    }
   
     @Id 
    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="Nom", length=254)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    
    @Column(name="Type", length=1)
    public Character getType() {
        return this.type;
    }
    
    public void setType(Character type) {
        this.type = type;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ecole")
    public Set<Diplome> getDiplomes() {
        return this.diplomes;
    }
    
    public void setDiplomes(Set<Diplome> diplomes) {
        this.diplomes = diplomes;
    }




}


