package com.sqli.rh_manager.entities;
// Generated Dec 19, 2013 6:37:54 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Niveau generated by hbm2java
 */
@Entity
@Table(name="niveau"
    ,catalog="rh_manager"
)
public class Niveau  implements java.io.Serializable {


     private int id;
     private String niveau;
     private Set<Diplome> diplomes = new HashSet<Diplome>(0);

    public Niveau() {
    }

	
    public Niveau(int id) {
        this.id = id;
    }
    public Niveau(int id, String niveau, Set<Diplome> diplomes) {
       this.id = id;
       this.niveau = niveau;
       this.diplomes = diplomes;
    }
   
     @Id 
    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="Niveau", length=254)
    public String getNiveau() {
        return this.niveau;
    }
    
    public void setNiveau(String niveau) {
        this.niveau = niveau;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="niveau")
    public Set<Diplome> getDiplomes() {
        return this.diplomes;
    }
    
    public void setDiplomes(Set<Diplome> diplomes) {
        this.diplomes = diplomes;
    }




}


