package com.sqli.rh_manager.entities;
// Generated Dec 19, 2013 6:37:54 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PosteSalaire generated by hbm2java
 */
@Entity
@Table(name="poste_salaire"
    ,catalog="rh_manager"
)
public class PosteSalaire  implements java.io.Serializable {


     private int id;
     private Collaborateur collaborateur;
     private String posteActuel;
     private Float salaireActuel;
     private Date dateElevation;

    public PosteSalaire() {
    }

	
    public PosteSalaire(int id, Collaborateur collaborateur) {
        this.id = id;
        this.collaborateur = collaborateur;
    }
    public PosteSalaire(int id, Collaborateur collaborateur, String posteActuel, Float salaireActuel, Date dateElevation) {
       this.id = id;
       this.collaborateur = collaborateur;
       this.posteActuel = posteActuel;
       this.salaireActuel = salaireActuel;
       this.dateElevation = dateElevation;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Collaborateur", nullable=false)
    public Collaborateur getCollaborateur() {
        return this.collaborateur;
    }
    
    public void setCollaborateur(Collaborateur collaborateur) {
        this.collaborateur = collaborateur;
    }
    
    @Column(name="Poste__actuel", length=254)
    public String getPosteActuel() {
        return this.posteActuel;
    }
    
    public void setPosteActuel(String posteActuel) {
        this.posteActuel = posteActuel;
    }
    
    @Column(name="Salaire_actuel", precision=12, scale=0)
    public Float getSalaireActuel() {
        return this.salaireActuel;
    }
    
    public void setSalaireActuel(Float salaireActuel) {
        this.salaireActuel = salaireActuel;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_elevation", length=19)
    public Date getDateElevation() {
        return this.dateElevation;
    }
    
    public void setDateElevation(Date dateElevation) {
        this.dateElevation = dateElevation;
    }




}


