package com.sqli.rh_manager.entities;
// Generated Dec 19, 2013 6:37:54 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name="profile"
    ,catalog="rh_manager"
)
public class Profile  implements java.io.Serializable {


     private int id;
     private String profile;
     private Set<Droit> droits = new HashSet<Droit>(0);
     private Set<Compte> comptes = new HashSet<Compte>(0);

    public Profile() {
    }

	
    public Profile(int id) {
        this.id = id;
    }
    public Profile(int id, String profile, Set<Droit> droits, Set<Compte> comptes) {
       this.id = id;
       this.profile = profile;
       this.droits = droits;
       this.comptes = comptes;
    }
   
     @Id 
    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="Profile", length=254)
    public String getProfile() {
        return this.profile;
    }
    
    public void setProfile(String profile) {
        this.profile = profile;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="profile_droit", catalog="rh_manager", joinColumns = { 
        @JoinColumn(name="Profile", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Droit", nullable=false, updatable=false) })
    public Set<Droit> getDroits() {
        return this.droits;
    }
    
    public void setDroits(Set<Droit> droits) {
        this.droits = droits;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="profile")
    public Set<Compte> getComptes() {
        return this.comptes;
    }
    
    public void setComptes(Set<Compte> comptes) {
        this.comptes = comptes;
    }




}


