package com.sqli.rh_manager.entities;
// Generated Dec 19, 2013 6:37:54 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Technologie generated by hbm2java
 */
@Entity
@Table(name="technologie"
    ,catalog="rh_manager"
)
public class Technologie  implements java.io.Serializable {


     private int id;
     private String technologie;
     private Set<TechnologiesMaitrisees> technologiesMaitriseeses = new HashSet<TechnologiesMaitrisees>(0);

    public Technologie() {
    }

	
    public Technologie(int id) {
        this.id = id;
    }
    public Technologie(int id, String technologie, Set<TechnologiesMaitrisees> technologiesMaitriseeses) {
       this.id = id;
       this.technologie = technologie;
       this.technologiesMaitriseeses = technologiesMaitriseeses;
    }
   
     @Id 
    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="Technologie", length=254)
    public String getTechnologie() {
        return this.technologie;
    }
    
    public void setTechnologie(String technologie) {
        this.technologie = technologie;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="technologie")
    public Set<TechnologiesMaitrisees> getTechnologiesMaitriseeses() {
        return this.technologiesMaitriseeses;
    }
    
    public void setTechnologiesMaitriseeses(Set<TechnologiesMaitrisees> technologiesMaitriseeses) {
        this.technologiesMaitriseeses = technologiesMaitriseeses;
    }




}


