package com.sqli.rh_manager.entities;
// Generated Dec 19, 2013 6:37:54 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TechnologiesMaitrisees generated by hbm2java
 */
@Entity
@Table(name="technologies_maitrisees"
    ,catalog="rh_manager"
)
public class TechnologiesMaitrisees  implements java.io.Serializable {


     private TechnologiesMaitriseesId id;
     private Technologie technologie;
     private Collaborateur collaborateur;
     private Integer niveauExpertise;

    public TechnologiesMaitrisees() {
    }

	
    public TechnologiesMaitrisees(TechnologiesMaitriseesId id, Technologie technologie, Collaborateur collaborateur) {
        this.id = id;
        this.technologie = technologie;
        this.collaborateur = collaborateur;
    }
    public TechnologiesMaitrisees(TechnologiesMaitriseesId id, Technologie technologie, Collaborateur collaborateur, Integer niveauExpertise) {
       this.id = id;
       this.technologie = technologie;
       this.collaborateur = collaborateur;
       this.niveauExpertise = niveauExpertise;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="technologie", column=@Column(name="Technologie", nullable=false) ), 
        @AttributeOverride(name="collaborateur", column=@Column(name="Collaborateur", nullable=false) ) } )
    public TechnologiesMaitriseesId getId() {
        return this.id;
    }
    
    public void setId(TechnologiesMaitriseesId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Technologie", nullable=false, insertable=false, updatable=false)
    public Technologie getTechnologie() {
        return this.technologie;
    }
    
    public void setTechnologie(Technologie technologie) {
        this.technologie = technologie;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Collaborateur", nullable=false, insertable=false, updatable=false)
    public Collaborateur getCollaborateur() {
        return this.collaborateur;
    }
    
    public void setCollaborateur(Collaborateur collaborateur) {
        this.collaborateur = collaborateur;
    }
    
    @Column(name="niveau_expertise")
    public Integer getNiveauExpertise() {
        return this.niveauExpertise;
    }
    
    public void setNiveauExpertise(Integer niveauExpertise) {
        this.niveauExpertise = niveauExpertise;
    }




}


